// ignore_for_file: public_member_api_docs,constant_identifier_names,type=lint,unused_element,unused_field
import 'package:flutter/foundation.dart';

//
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// Generated by flutter-assets-generator extension for VS Code
// @mrasityilmaz
// **************************************************************************

@immutable
final class Assets {
  Assets._();
  static final _Fonts fonts = _Fonts._();
  static final _Images images = _Images._();
}

@immutable
final class _Fonts {
  _Fonts._();

  final String manrope_bold_ttf = 'assets\fonts\Manrope-Bold.ttf';
  final String manrope_light_ttf = 'assets\fonts\Manrope-Light.ttf';
  final String manrope_medium_ttf = 'assets\fonts\Manrope-Medium.ttf';
  final String manrope_regular_ttf = 'assets\fonts\Manrope-Regular.ttf';
  final String manrope_semibold_ttf = 'assets\fonts\Manrope-SemiBold.ttf';
  final String vazirmatn_bold_ttf = 'assets\fonts\Vazirmatn-Bold.ttf';
  final String vazirmatn_light_ttf = 'assets\fonts\Vazirmatn-Light.ttf';
  final String vazirmatn_medium_ttf = 'assets\fonts\Vazirmatn-Medium.ttf';
  final String vazirmatn_regular_ttf = 'assets\fonts\Vazirmatn-Regular.ttf';
  final String vazirmatn_semibold_ttf = 'assets\fonts\Vazirmatn-SemiBold.ttf';
}

@immutable
final class _Images {
  _Images._();

  final String logo_png = 'assets/images/logo.png';
  final String onboarding_1_png = 'assets/images/onboarding_1.png';
  final String onboarding_2_png = 'assets/images/onboarding_2.png';
  final String onboarding_events_png = 'assets/images/onboarding_events.png';
  final String onboarding_formal_png = 'assets/images/onboarding_formal.png';
  final String onboarding_hybrid_png = 'assets/images/onboarding_hybrid.png';
  final String onboarding_office_png = 'assets/images/onboarding_office.png';
  final String onboarding_weekends_png =
      'assets/images/onboarding_weekends.png';
  final String splash_png = 'assets/images/splash.png';
}
